### ISSUE TITLE
Foundations: Fix the given example on Fibonacci series in README.md of Javascript exercise(Fundamentals: Part 5)

### ISSUE THREAD

**Issue by RushilJalal** [TheOdinProject/javascript-exercises#381]
### Describe your suggestion

There is a typo where the given Fibonacci series example in the README.md file says:

> A series of numbers in which each number ( Fibonacci number ) is the sum of the two preceding numbers. The simplest is the series 1, 1, 2, 3, 5, 8, etc.
After completing the exercise, I checked the solution to find that 0 was taken to be the first term of the series.
I googled it and confirmed that Fibonacci series starts from 0.
I am attaching required screenshots.

![image](https://github.com/TheOdinProject/curriculum/assets/54212357/af1e35cb-bf1e-4af1-a6e0-8eae90184598)
![image](https://github.com/TheOdinProject/curriculum/assets/54212357/b0f50639-6418-4cc2-b3e6-287c71a4bcda)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-5#assignment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

willyWonka

### (Optional) Additional Comments

This is my first time contributing here so any help will be appreciated!

**Comment by RushilJalal** [comment]
@thatblindgeye 

> transferred this issue from TheOdinProject/curriculum

I don't get what this means. Could you please explain?
Also, I'm having trouble finding the location of the file I'm trying to fix. It's the README.md in the javascript testing of Fibonacci in Foundations: Javascript Part 5. If you could please let me know the location of the testing section, I would be grateful. Thanks!

**Comment by RushilJalal** [comment]
> The title of the PR must follow the format described in the PR template.
I found this in the Contributing Guide but I didn't find anything in the template related to the PR title.

**Comment by thatblindgeye** [comment]
>I don't get what this means. Could you please explain?

That just means the issue was moved from one repo to another.

> have another question. In this case I want to be working with TheOdinProject/javascript-exercises.
We were earlier required to fork and clone this repo to complete the exercise so I had an existing clone on my machine. In my case, I deleted the pre-existing clone and made a new one since the old one had my completed exercises.
In another case, what if I was still doing the exercises and couldn't delete the clone on my machine? What would have been the best case to go forward with making the fix without causing problems.
Sorry I'm just new to this.

Typically if you already have a clone you don't need to delete + re-clone. Depending where you're at in the curriculum it may not have been covered yet, but utilizing branches would be the way to go in the future. If you haven't gotten to that point yet don't worry, I believe it comes up in the Revisiting Rock Paper Scissors lesson in Foundations.

**Comment by RushilJalal** [comment]
@thatblindgeye Actually, using branches has already been covered but I think it makes sense to use branching when you want to add a feature which you don't to be a part of `main` branch yet.
But in my case, if I created a branch, it would consist of the exercises I completed earlier, right?
How do I make sure that the clone I'm working with doesn't have the exercises completed by me?

**Comment by thatblindgeye** [comment]
@RushilJalal It depends what exactly your local clone looks like. If you didn't commit your solutions to the exercises then you could create a new branch and commit them on that new branch, or you could stash them. If you committed your solutions locally then you could create a new branch based off your main branch, then revert your main branch prior to your commit.

Though ideally getting into the habit of working on non-`main` branches is a good one to get used to.

**Comment by RushilJalal** [comment]
@thatblindgeye Thanks a lot!
