### ISSUE TITLE
Add Spanish translation

### ISSUE THREAD

**Issue by Federico-Taborda** [TheOdinProject/javascript-exercises#429]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Exercises: Add exercise on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Hello, I am new to contributing to open source. I am Spanish-speaking and I would like to be able to contribute to this repository to translate it into my language so that it reaches more people and they can benefit from it. I am looking forward to your response :)

**2. Acceptance Criteria:**

**3. Additional Information:**

**Comment by CouchofTomato** [comment]
Hey @Federico-Taborda 

I love your enthusiasm, nothing would make us happier than to roll this out to other languages. However, we've explored this in the past and the main barrier is that it would need to be maintained because the lessons do periodically change. Therefore it's too much of an ask to keep them in sync.

There is nothing stopping you forking and translating, but it can't be offically hosted by TOP.

**Comment by Federico-Taborda** [comment]
Thank you for your time to respond. I understand the limitations, I will translate what I can and if I see any changes in the exercises I will correct them

**Comment by thatblindgeye** [comment]
Closing per answer in previous comments
