### ISSUE TITLE
Change number to integer in sumAll problem statement

### ISSUE THREAD

**Issue by weboffools** [TheOdinProject/javascript-exercises#476]
The problem statement says: 
"Implement a function that takes 2 positive integers and returns the sum of every number between (and including) them"

It should say:
"Implement a function that takes 2 positive integers and returns the sum of every *integer* between (and including) them"

**Comment by MaoShizhong** [comment]
Thanks for the clarification @weboffools. Would you like to be assigned to this?
(Also please fill out the issue form next time)

**Comment by weboffools** [comment]
@MaoShizhong I can be assigned to this but won't get to it for a week or two. Sorry I forgot about the issue form; I was here in the repo helping someone and it seemed natural to open the issue from here. You mean the form linked from "Report an Issue" in the lesson I assume?

**Comment by MaoShizhong** [comment]
@weboffools If you use the "new issue" button here, you'll be brought to a selection of "Bug report" or "feature request", where you'll get a form. In this case, this issue could be argued for either of those options as it's both a general clarification, but also arguable that "number" is technically incorrect so is a bug.

If you know you won't be able to get round to it for a bit, I'll open this up to assignment request. When you get time again, if this issue is still looking for help, then feel free to comment to be assigned :)

**Comment by weboffools** [comment]
Ok good, thanks for the info on that.

**Comment by leu1** [comment]
I can take care of this if its still available, can I be assigned to it?

**Comment by MaoShizhong** [comment]
@leu1 all yours!
