### ISSUE TITLE
README.md hint doesn't match solution.js

### ISSUE THREAD

**Issue by jveneziano25** [TheOdinProject/javascript-exercises#482]
In Exercise 06 - leapYears, the README file has a hint that says "use an `if` statement and `&&` to make sure all the conditions are met properly". However, the solution.js file doesn't even use an if statement, which can lead to confusion.

**Comment by MaoShizhong** [comment]
Thanks @jveneziano25.
Agreed that the current solution will be better replaced with something that's more intuitive and recognisable for most people at this point in the curriculum, i.e. using conditionals rather than returning a single complex boolean expression.

The solution I'd propose is:
```js
const leapYears = function (year) {
  const isYearDivisibleByFour = year % 4 === 0;
  const isCentury = year % 100 === 0;
  const isYearDivisibleByFourHundred = year % 400 === 0;

  if (
    isYearDivisibleByFour &&
    (!isCentury || isYearDivisibleByFourHundred)
  ) {
    return true;
  } else {
    return false;
  }
};

module.exports = leapYears;
```

Let me know if you're happy to open a pull request with this change to the exercise's solution file or not, then I can assign you or open this up for assignment.

**Comment by jveneziano25** [comment]
Sure, I would be happy to open a pull request for this and I think your suggestion is much clearer for the current structure of the program.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MaoShizhong** [comment]
Go for it
